types:
  # By default types specified in commitizen/conventional-commit-types is used.
  # See: https://github.com/commitizen/conventional-commit-types/blob/v2.2.0/index.json
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
  # custom
  - improve
