name: pr-ci

on:
  pull_request:
    branches: [master]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - run: yarn -s test:unit

  system-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        run: yarn --frozen-lockfile
      - run: yarn -s build
      - name: Setup global git user
        run: |
          # For nexus create app flow which will make an init commit 
          git config --global user.name prisma-labs
          git config --global user.email labs@prisma.io
      - run: |
          # For Node 10.x we require worker threads
          if [[ "$(node -v)" =~ v10 ]]; then
            echo 'alias node="node --experimental-worker"' >> "$HOME/.bash_profile"
            source "$HOME/.bash_profile"
          fi
          yarn -s test:system
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v1
      - shell: bash -l {0}
        run: |
          yarn -s test:system
